### ISSUE TITLE
color.js

### ISSUE THREAD

**Issue by nuxodin** [siteroller/ColorRoller-MooTools-Color-Picker#2]
Are the extenstions to "fromRgb" and "toRgb" planet vor next mootools-more releases?
If not, i think its better to put them to the ColorRoller.js

**Comment by siteroller** [comment]
These functions are part of my own fork of mootools more.  I hope they will eventually make it into the -More codebase, but don't have the credentials to push it myself.

For now, the Color.js file included in the repo is a drag & drop replacement for the version of Color.js that is part of -More.  It is fully backwards compatible and can be used safely in place of the existing file.

I left all this out of the docs by accident - hopefully tomorrow I will get that in.
