### ISSUE TITLE
IE8 Unable to click (change) color gradient

### ISSUE THREAD

**Issue by fyrye** [siteroller/ColorRoller-MooTools-Color-Picker#3]
Testing in IE8 and unable to click the color map gradients to change the color, works in Chrome, and FF however. (.crBox)
The slider bar for HSL works fine however (.crBar)
No Errors, just doesn't provide the function.

Thanks for the work on the project.

**Comment by fyrye** [comment]
As a side note this issue does occur on the demo page.
http://siteroller.net/projects/colorpicker/Demo/

**Comment by teoCMS** [comment]
i got the same error.
To make it work under IE, this is what i did:
Edit ColorRoller.js, go to the end of that 'evil with' loop and enter the following: crShade.set('opacity', '0.001'); 
Go few lines up and change adopt sequence,  'crShade' should be before 'crImg'.

Edit ColorRoller.css file and add background-color to .crShade. 
What You want to achieve is to adopt .crShade before .crImg and make it NOT 100% opaque so it can grab click event in IE. So i added some z-index rules to .crShade and .crImg. crShade should be above crImg

Done, works

**Comment by siteroller** [comment]
Thanks. If you fork and edit, send me a pull request.
